learned how to decrypt ops manager

diff --git a/boshctl b/boshctl
--- a/boshctl
+++ b/boshctl
@@ -32,11 +32,27 @@ is_logged_in() {
   ! $(bosh status | grep -q 'not logged in')
 }
 
+is_opsman_locked() {
+  $(curl "https://localhost/" -k -I -s | grep -q 'Location: .*/unlock')
+}
+
+unlock_opsman() {
+  local PASSPHRASE=$1
+
+  local STATUS_CODE=$(curl "https://localhost/api/v0/unlock" -k \
+    -s -o /dev/null -w "%{http_code}" \
+    -X PUT \
+    -H "Content-Type: application/json" \
+    -d "{\"passphrase\": \"$PASSPHRASE\"}")
+
+    [ "200" = "$STATUS_CODE" ]
+}
+
 is_valid_access_token() {
   local UAA_ACCESS_TOKEN=$1
   [ -n "$UAA_ACCESS_TOKEN" ] || return 1
 
-  local STATUS_CODE=$(curl http://localhost/uaa/check_token -k -L -G \
+  local STATUS_CODE=$(curl "https://localhost/uaa/check_token" -k -L -G \
     -s -o /dev/null -w "%{http_code}" \
     -u "opsman:" \
     -d token_type=bearer \
@@ -51,6 +67,7 @@ login_to_uaac() {
 
   local OPSMAN_PASS=
   read -r -s -p "Ops Manager Pass: " OPSMAN_PASS
+  echo # extra linefeed
 
   uaac target https://localhost/uaa --skip-ssl-validation
 
@@ -88,6 +105,15 @@ login() {
     local director_url=
     read -r -p "Director URL: " director_url
     bosh -n --ca-cert /var/tempest/workspaces/default/root_ca_certificate target $director_url
+  fi
+  if is_opsman_locked; then
+    local passphrase=
+    read -r -s -p "Ops Manager Decryption Passphrase: " passphrase
+    echo # extra linefeed
+    if ! unlock_opsman "$passphrase"; then
+      echo "Failed to unlock Ops Manager. Please try again."
+      exit 1
+    fi
   fi
   if ! is_logged_in; then
     login_via_opsmgr
